### ISSUE TITLE
Linking compile output back into project

### ISSUE THREAD

**Issue by endevagames** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#120]
I wanted to implement RCC for the scripting system in my game and not for the whole engine. I have a game project and an engine project. The game project uses the Engine project as a static library. In the engine project, things such as Cameras are defined. They are not defined in the game project, they are accessed through the static library. Now when compiling scripts, since the symbols for things such as the methods a Camera has are defined in the Engine project, the linker fails. Is there a way to resolve the external symbols defined in the Engine when compiling the scripts (Linking to the .lib of the engine kind of works but the new module sort of runs in it's own context and I also have to link all the libraries that the Engine uses)?

**Comment by dougbinks** [comment]
One solution to this would be to make the Engine a dynamically linked library.

If you stick with a static library then as you note you'll need to link with the library and any dependencies.

It is also possible to architecture your engine and game code so that it is easier to use with RCC++:

1. Define simple functionality inline in headers.
2. Use pure virtual interfaces for more complex functionality.
3. Use data driven approaches - for example calling a single virtual function passing an array of data is better than calling it many times for each item.
4. Use message passing - I use a simple message passing approach in my Avoyd engine which both avoids linking and also simplifies network programming.
5. Use runtime [Runtime source dependencies](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Runtime-source-dependencies) for libraries with a single source file.

Make sure to read the wiki sections on [Using libraries from runtime modifiable classes](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Using-libraries-from-runtime-modifiable-classes) and [Runtime source dependencies](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Runtime-source-dependencies).

**Comment by endevagames** [comment]
Hmm... thanks for the advice. I'll look into linking to the engine as a dll when in development mode and then linking as a static lib when distributing the game. I think that might end up being a good compromise without having to do a facelift on how the engine works. I'll also look into seeing if I can make some of my systems System Table compatible as well. Thank you!

**Comment by dougbinks** [comment]
I'm closing this issue as answered.
