### ISSUE TITLE
Deriving RCCpp Compilation

### ISSUE THREAD

**Issue by Platforming-Mayhem** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#127]
Hi there, I am currently having an issue with the syntax of RCCpp. First off the REGISTERCLASS macro doesn't work when the class is within a namespace
![image](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/assets/82027284/208588f1-afc5-4ca9-af27-196579962045)
Then second of all I can no longer instantiate this derived class normally, since it gives this issue
![image](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/assets/82027284/6ca18225-c210-43df-af75-52b8b0fbf32a)
I would really appreciate some help on fixing this :)

**Comment by dougbinks** [comment]
Hi @Platforming-Mayhem,


## Namespaces
I'll take a look at fixing this at some point, but for now there is a workaround:

```C++
// in a .cpp file:
using namespace K;
REGISTERCLASS(Component);
```

##  Constructing
You cannot construct RuntimeCompiledCPlusPlus objects using `new` this way.

To construct an `IObject` derived class you need to use the constructor:

```C++
IObject* pObj = 0;
IObjectConstructor* pConstructor = 
PerModuleInterface::g_pRuntimeObjectSystem->GetObjectFactorySystem()->GetConstructor( "Sprite" ); // name is not namepaced due to above issue
pObj = pConstructor->Construct();
K::Sprite* pSprite = 0;
pObj->GetInterface( &pSprite );
```

See the [ConsoleExample.cpp](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/master/Aurora/Examples/ConsoleExample/ConsoleGame.cpp) for a simple example.

You can make the above into a template class. There are also ways to make it a static member of the interface for the class. If you want to improve the performance of construction by storing the constructor for each type then remember you will need to reacquire them when the Runtime Compiler runs, again see the ConsoleExample and the `OnConstructorsAdded` callback.

A proposal which would be a larger change to your codebase is to consider using an Entity Component System approach where each entity is just an identifier value, and the components are singletons which own an array of their children indexed by the entity identifier. Components usually have a map of entityids to components in some way so the array of components is not the size of all entities for all components. 

There is a relatively short overview of this technique in the following posts:
[Building a Data-Oriented Entity System (part 1)](http://bitsquid.blogspot.com/2014/08/building-data-oriented-entity-system.html)
[Building a Data-Oriented Entity System (part 2)](http://bitsquid.blogspot.com/2014/09/building-data-oriented-entity-system.html)

This is what I use in Avoyd.

Note that it is better to submit each issue separately on Github rather than together like this as then it will be easier to track resolution of them.

**Comment by Platforming-Mayhem** [comment]
![image](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/assets/82027284/6e20218b-2c9d-4de6-8bd2-dc86ada6e93a)
I'm getting this error now instead, any idea why it's happening?

**Comment by dougbinks** [comment]
It looks like the constructor for "Sprite" was not registered.

You can use the following code after initializing RCC++ to check which constructors you have registered:

```C++
AUDynArray<IObjectConstructor*> constructors;
PerModuleInteraface::g_pRuntimeObjectSystem->GetObjectFactorySystem()->GetAll( constructors );
for(int i = 0; i < constructors.Size(); ++i )
{
     PerModuleInteraface::g_pRuntimeObjectSystem->GetLogger()->LogInfo("Constructor %d: Name: %s\n", i, constructors[i]->GetName() );
}
```

Alternatively you can put a breakpoint in `ObjectFactorySystem::AddConstructors` in `ObjectFactorySystem.cpp` line 248 or so and check what the constructors being assigned are.

**Comment by Platforming-Mayhem** [comment]
cool, thank you this helped alot :)
